/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame;

/**
 *
 * @author NB-3170
 */
public class Ventana_Principal extends javax.swing.JFrame {

    /**
     * Creates new form Ventana_Principal
     */
    public Ventana_Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        Visu_Propietario = new javax.swing.JMenuItem();
        edit_Propietarios = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        visu_citas = new javax.swing.JMenuItem();
        edit_citas = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        visu_vehiculos = new javax.swing.JMenuItem();
        edit_vehiculos = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        visu_Inventario = new javax.swing.JMenuItem();
        edit_inventario = new javax.swing.JMenuItem();
        jMenu13 = new javax.swing.JMenu();
        jMenu14 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        edit_factura = new javax.swing.JMenuItem();
        edit_detalle_fac = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        edit_factura_detalle = new javax.swing.JMenuItem();
        jMenu15 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        edit_presupuesto = new javax.swing.JMenuItem();
        Detalle_Presupuesto_principal = new javax.swing.JMenu();
        visualiza_det_presupuesto = new javax.swing.JMenuItem();
        editar_detaPresupuesto = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        visu_mecanico = new javax.swing.JMenuItem();
        edit_mecanico = new javax.swing.JMenuItem();
        jMenu10 = new javax.swing.JMenu();
        jMenu11 = new javax.swing.JMenu();
        visu_respuesto = new javax.swing.JMenuItem();
        edit_repuesto = new javax.swing.JMenuItem();
        jMenu12 = new javax.swing.JMenu();
        visua_proveedores = new javax.swing.JMenuItem();
        edit_proveedores = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        escritorio.setPreferredSize(new java.awt.Dimension(1022, 632));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/escritorio img.png"))); // NOI18N

        escritorio.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1)
        );

        getContentPane().add(escritorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, -1));

        jMenu1.setText("Usuarios");

        jMenu3.setText("Propietarios");
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });

        Visu_Propietario.setText("Visualizar Lista");
        Visu_Propietario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Visu_PropietarioActionPerformed(evt);
            }
        });
        jMenu3.add(Visu_Propietario);

        edit_Propietarios.setText("Agregar & Editar Propietarios");
        edit_Propietarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_PropietariosActionPerformed(evt);
            }
        });
        jMenu3.add(edit_Propietarios);

        jMenu1.add(jMenu3);

        jMenu4.setText("Citas de Propietarios");

        visu_citas.setText("Visualizar lista");
        visu_citas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visu_citasActionPerformed(evt);
            }
        });
        jMenu4.add(visu_citas);

        edit_citas.setText("Agregar & Editar Citas");
        edit_citas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_citasActionPerformed(evt);
            }
        });
        jMenu4.add(edit_citas);

        jMenu1.add(jMenu4);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Vehículos");

        jMenu6.setText("Vehiculos");

        visu_vehiculos.setText("Visualizar Lista");
        visu_vehiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visu_vehiculosActionPerformed(evt);
            }
        });
        jMenu6.add(visu_vehiculos);

        edit_vehiculos.setText("Agregar & Editar");
        edit_vehiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_vehiculosActionPerformed(evt);
            }
        });
        jMenu6.add(edit_vehiculos);

        jMenu2.add(jMenu6);

        jMenu7.setText("Inventario Vehiculos");
        jMenu7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu7ActionPerformed(evt);
            }
        });

        visu_Inventario.setText("Visualizar Inventario");
        visu_Inventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visu_InventarioActionPerformed(evt);
            }
        });
        jMenu7.add(visu_Inventario);

        edit_inventario.setText("Agregar & Editar");
        edit_inventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_inventarioActionPerformed(evt);
            }
        });
        jMenu7.add(edit_inventario);

        jMenu2.add(jMenu7);

        jMenuBar1.add(jMenu2);

        jMenu13.setText("Administración");

        jMenu14.setText("Factura");

        jMenuItem1.setText("Visualizar");
        jMenu14.add(jMenuItem1);

        edit_factura.setText("Editar & Agregar");
        jMenu14.add(edit_factura);

        jMenu13.add(jMenu14);

        edit_detalle_fac.setText("Detalle Facturas");

        jMenuItem5.setText("Visualizar");
        edit_detalle_fac.add(jMenuItem5);

        edit_factura_detalle.setText("Editar & Agregar");
        edit_detalle_fac.add(edit_factura_detalle);

        jMenu13.add(edit_detalle_fac);

        jMenu15.setText("Presupuesto");

        jMenuItem3.setText("Visualizar");
        jMenu15.add(jMenuItem3);

        edit_presupuesto.setText("Editar & Agregar");
        jMenu15.add(edit_presupuesto);

        jMenu13.add(jMenu15);

        Detalle_Presupuesto_principal.setText("Detalle Presupuesto");
        Detalle_Presupuesto_principal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Detalle_Presupuesto_principalActionPerformed(evt);
            }
        });

        visualiza_det_presupuesto.setText("Visualizar");
        visualiza_det_presupuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visualiza_det_presupuestoActionPerformed(evt);
            }
        });
        Detalle_Presupuesto_principal.add(visualiza_det_presupuesto);

        editar_detaPresupuesto.setText("Editar & Agregar");
        editar_detaPresupuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editar_detaPresupuestoActionPerformed(evt);
            }
        });
        Detalle_Presupuesto_principal.add(editar_detaPresupuesto);

        jMenu13.add(Detalle_Presupuesto_principal);

        jMenuBar1.add(jMenu13);

        jMenu8.setText("Mecánico");

        jMenu9.setText("Mecánico");

        visu_mecanico.setText("Visualizar");
        visu_mecanico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visu_mecanicoActionPerformed(evt);
            }
        });
        jMenu9.add(visu_mecanico);

        edit_mecanico.setText("Agregar & Editar");
        edit_mecanico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_mecanicoActionPerformed(evt);
            }
        });
        jMenu9.add(edit_mecanico);

        jMenu8.add(jMenu9);

        jMenuBar1.add(jMenu8);

        jMenu10.setText("Repuestos");

        jMenu11.setText("Lista de Repuestos");

        visu_respuesto.setText("Visualizar");
        visu_respuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visu_respuestoActionPerformed(evt);
            }
        });
        jMenu11.add(visu_respuesto);

        edit_repuesto.setText("Agregar & Editar");
        edit_repuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_repuestoActionPerformed(evt);
            }
        });
        jMenu11.add(edit_repuesto);

        jMenu10.add(jMenu11);

        jMenu12.setText("Proveedores");

        visua_proveedores.setText("Visualizar Lista");
        jMenu12.add(visua_proveedores);

        edit_proveedores.setText("Editar & Agregar");
        edit_proveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_proveedoresActionPerformed(evt);
            }
        });
        jMenu12.add(edit_proveedores);

        jMenu10.add(jMenu12);

        jMenuBar1.add(jMenu10);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editar_detaPresupuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editar_detaPresupuestoActionPerformed
        Detalle_Presupuesto ver_ventana = new Detalle_Presupuesto();
        escritorio.add(ver_ventana);
        ver_ventana.show();


    }//GEN-LAST:event_editar_detaPresupuestoActionPerformed

    private void Detalle_Presupuesto_principalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Detalle_Presupuesto_principalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Detalle_Presupuesto_principalActionPerformed

    private void visualiza_det_presupuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visualiza_det_presupuestoActionPerformed
        Visu_Detalle_Presupuesto ver_ventana = new Visu_Detalle_Presupuesto();
        escritorio.add(ver_ventana);
        ver_ventana.show();
    }//GEN-LAST:event_visualiza_det_presupuestoActionPerformed

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu3ActionPerformed

    private void Visu_PropietarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Visu_PropietarioActionPerformed
        Visu_Propietario ver_ventana = new Visu_Propietario();
        escritorio.add(ver_ventana);
        ver_ventana.show();
    }//GEN-LAST:event_Visu_PropietarioActionPerformed

    private void edit_PropietariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_PropietariosActionPerformed
        // TODO add your handling code here:
        Edit_Propietario ver_ventana = new Edit_Propietario();
        escritorio.add(ver_ventana);
        ver_ventana.show();
    }//GEN-LAST:event_edit_PropietariosActionPerformed

    private void edit_citasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_citasActionPerformed
        Edit_Citas ver_ventana = new Edit_Citas();
        escritorio.add(ver_ventana);
        ver_ventana.show();
    }//GEN-LAST:event_edit_citasActionPerformed

    private void visu_citasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visu_citasActionPerformed
        Visu_Citas ver_ventana = new Visu_Citas();
        escritorio.add(ver_ventana);
        ver_ventana.show();
    }//GEN-LAST:event_visu_citasActionPerformed

    private void edit_vehiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_vehiculosActionPerformed
        // TODO add your handling code here:
        Edit_Vehiculos ver_ventana = new Edit_Vehiculos();
        escritorio.add(ver_ventana);
        ver_ventana.show();
    }//GEN-LAST:event_edit_vehiculosActionPerformed

    private void visu_vehiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visu_vehiculosActionPerformed
        // TODO add your handling code here:
        Visu_Vehiculos ver_ventana = new Visu_Vehiculos();
        escritorio.add(ver_ventana);
        ver_ventana.show();
    }//GEN-LAST:event_visu_vehiculosActionPerformed

    private void jMenu7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu7ActionPerformed

    private void edit_inventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_inventarioActionPerformed
        // TODO add your handling code here:
        Edit_Inventario ver_ventana = new Edit_Inventario();
        escritorio.add(ver_ventana);
        ver_ventana.show();
    }//GEN-LAST:event_edit_inventarioActionPerformed

    private void visu_InventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visu_InventarioActionPerformed
        // TODO add your handling code here:
        Visu_Inventario ver_ventana = new Visu_Inventario();
        escritorio.add(ver_ventana);
        ver_ventana.show();
    }//GEN-LAST:event_visu_InventarioActionPerformed

    private void visu_mecanicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visu_mecanicoActionPerformed
        // TODO add your handling code here:
        Visu_Mecanico ver_ventana = new Visu_Mecanico();
        escritorio.add(ver_ventana);
        ver_ventana.show();

    }//GEN-LAST:event_visu_mecanicoActionPerformed

    private void edit_mecanicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_mecanicoActionPerformed
        // TODO add your handling code here:
        Edit_Mecanico ver_ventana = new Edit_Mecanico();
        escritorio.add(ver_ventana);
        ver_ventana.show();
    }//GEN-LAST:event_edit_mecanicoActionPerformed

    private void visu_respuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visu_respuestoActionPerformed
        // TODO add your handling code here:
        Visu_Repuestos ver_ventana = new Visu_Repuestos();
        escritorio.add(ver_ventana);
        ver_ventana.show();

    }//GEN-LAST:event_visu_respuestoActionPerformed

    private void edit_repuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_repuestoActionPerformed
        // TODO add your handling code here:
        Edit_Repuestos ver_ventana = new Edit_Repuestos();
        escritorio.add(ver_ventana);
        ver_ventana.show();
    }//GEN-LAST:event_edit_repuestoActionPerformed

    private void edit_proveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_proveedoresActionPerformed
        // TODO add your handling code here:
        Edit_Proveedores ver_ventana = new Edit_Proveedores();
        escritorio.add(ver_ventana);
        ver_ventana.show();
    }//GEN-LAST:event_edit_proveedoresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana_Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JMenu Detalle_Presupuesto_principal;
    public static javax.swing.JMenuItem Visu_Propietario;
    public static javax.swing.JMenuItem edit_Propietarios;
    public static javax.swing.JMenuItem edit_citas;
    public static javax.swing.JMenu edit_detalle_fac;
    public static javax.swing.JMenuItem edit_factura;
    public static javax.swing.JMenuItem edit_factura_detalle;
    public static javax.swing.JMenuItem edit_inventario;
    public static javax.swing.JMenuItem edit_mecanico;
    public static javax.swing.JMenuItem edit_presupuesto;
    public static javax.swing.JMenuItem edit_proveedores;
    public static javax.swing.JMenuItem edit_repuesto;
    public static javax.swing.JMenuItem edit_vehiculos;
    public static javax.swing.JMenuItem editar_detaPresupuesto;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JLabel jLabel1;
    public static javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu12;
    public static javax.swing.JMenu jMenu13;
    private javax.swing.JMenu jMenu14;
    private javax.swing.JMenu jMenu15;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    public static javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem visu_Inventario;
    public static javax.swing.JMenuItem visu_citas;
    private javax.swing.JMenuItem visu_mecanico;
    private javax.swing.JMenuItem visu_respuesto;
    private javax.swing.JMenuItem visu_vehiculos;
    private javax.swing.JMenuItem visua_proveedores;
    private javax.swing.JMenuItem visualiza_det_presupuesto;
    // End of variables declaration//GEN-END:variables
}
